routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('kontrakan', 'KontrakanController');
Route::resource('pemilik', 'PemilikController')->middleware('checkRole:pemilik');;
Route::resource('transaksi', 'TransaksiController');
Route::resource('penyewa', 'PenyewaController');

app/Pemilik.php
<?php

namespace App;
use Auth;
use Illuminate\Database\Eloquent\Model;

class Pemilik extends Model
{
    public function kontrakans()
    {
        return $this->hasMany('App\Kontrakan');
    }

    protected $table = "pemilik";
    protected $fillable = ["name", "alamat", "email", "norek", "user_id"];

}

app/Http/Controllers/PemilikController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Kontrakan;
use App\Pemilik;
use Auth;

class PemilikController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index','show');
        $this->middleware('checkRole:pemilik');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pemiliks = Pemilik::all();
        return view('pemilik.index', compact('pemiliks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pemilik.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'alamat'=>'required',
            'email'=>'required',
            'norek'=>'required'
        ]);

        $pemilik = Pemilik::create([
            "name"=> $request["name"],
            "alamat"=>$request["alamat"],
            "email"=>$request["email"],
            "norek"=>$request["norek"]
        ]);
        return redirect('/pemilik')->with('success', 'Berhasil Menambahkan Pemilik Baru!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pemilik = Pemilik::find($id);
        return view('pemilik.show', compact('pemilik'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pemilik = Pemilik::find($id);
        return view('pemilik.edit', compact('pemilik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'alamat'=>'required',
            'email'=>'required',
            'norek'=>'required'
        ]);

        $update = Pemilik::where('id', $id)->update([
            "name"=>$request["name"],
            "alamat"=>$request["alamat"],
            "email"=>$request["email"],
            "norek"=>$request["norek"]
        ]);
        return redirect('/pemilik')->with('success', 'Berhasil Merubah Data Pemilik!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pemilik::destroy($id);
        return redirect('/pemilik')->with('success', 'Data Pemilik  Berhasil Dihapus');
    }
}

resources/views/pemilik/create.blade.php
@extends('layouts.master')
@section('content')

<div class="ml-3 mt-3">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Daftar Sebagai Pemilik Baru</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/pemilik" method="POST">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Nama Pemilik</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ Auth::user()->name }}" placeholder="Masukkan Nama Anda">
                        @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" value="{{ old('alamat', '') }}" placeholder="Masukkan Alamat Anda">
                        @error('alamat')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="{{ old('email', '') }}" placeholder="Masukkan Alamat Email Anda">
                        @error('alamat')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="norek">No Rekening</label>
                        <input type="text" class="form-control" id="norek" name="norek" value="{{ old('norek', '') }}" placeholder="Masukkan No Rekening Anda">
                        @error('norek')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
     </div>
</div>

@endsection

resources/views/pemilik/edit.blade.php
@extends('layouts.master')
@section('content')

<div class="ml-3 mt-3">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Data Pemilik {{ $pemilik->name }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/kontrakan/{{ $pemilik->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Nama Pemilik</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $pemilik->name) }}" placeholder="Masukkan Nama Anda">
                        @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" value="{{ old('alamat', $pemilik->alamat) }}" placeholder="Masukkan Alamat Anda">
                        @error('alamat')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="{{ old('email', $pemilik->email) }}" placeholder="Masukkan Email Anda">
                        @error('email')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="norek">Norek</label>
                        <input type="text" class="form-control" id="norek" name="norek" value="{{ old('norek', $pemilik->norek) }}" placeholder="Masukkan Norek Anda">
                        @error('norek')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
     </div>
</div>

@endsection

resources/views/pemilik/index.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Daftar Pemilik Kontrakan</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      @if (session('success'))
          <div class="alert alert-success">
            {{( session ('success'))}}
          </div>
      @endif
      <a class="btn btn-info mb-4" href="{{ route('pemilik.create') }}">
        Daftar Sebagai Pemilik Kontrakan Baru
      </a>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th style="width: 200px">Nama Pemilik</th>
            <th>Alamat</th>
            <th>Email</th>
            <th>No Rekening</th>
            <th style="width: 120px">Actions</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($pemiliks as $key => $pemilik)
            <tr>
              <td> {{ $key + 1 }} </td>
              <td> {{ $pemilik->name }} </td>
              <td> {{ $pemilik->alamat }} </td>
              <td> {{ $pemilik->email }} </td>
              <td> {{ $pemilik->norek }} </td>
              @auth
              <td style="display : flex;"> 
                <a href="{{route('pemilik.show', ['pemilik' => $pemilik->id])}}" class="btn btn-info btn-sm"> Lihat </a>
                <a href="{{route('pemilik.edit', ['pemilik' => $pemilik->id])}}" class="btn btn-default btn-sm"> Edit </a>
                <form action="{{route('pemilik.destroy', ['pemilik' => $pemilik->id ])}}" method="post">
                  @csrf
                  @method('DELETE')
                  <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
              </td>
            </tr>
              @endauth
              @guest
              <td style="display : flex;"> 
              <a href="{{route('pemilik.show', ['pemilik' => $pemilik->id])}}" class="btn btn-info btn-sm"> Lihat </a>
              </td>
              @endguest
            @empty
              <tr>
                <td colspan="6" align="center"> Tidak Ada Daftar Pemilik </td>
              </tr>
          @endforelse
        </tbody>
      </table>
      
    </div>
    <!-- /.card-body -->
  </div>
</div>


@endsection

resources/views/pemilik/show.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
    <h2> Details Pemilik </h2>
    <p> {{ $pemilik->name }} </p>
    <p> {{ $pemilik->alamat }} </p>
    <p> {{ $pemilik->email }} </p>
    <p> {{ $pemilik->norek }} </p>
</div>
@endsection