routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('kontrakan', 'KontrakanController');
Route::resource('pemilik', 'PemilikController')->middleware('checkRole:pemilik');;
Route::resource('transaksi', 'TransaksiController');
Route::resource('penyewa', 'PenyewaController');

app/Transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    public function Penyewa(){
        return $this->belongsTo('App\Penyewa');
    }

    public function Kontrakan(){
        return $this->belongsTo('App\Kontrakan');
    }

    protected $table = "transaksi";
    protected $fillable = ["tgl_sewa", "harga", "jenis_sewa", "penyewa_id", "kontrakan_id"];
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Kontrakan;
use App\Penyewa;
use App\Transaksi;
use Illuminate\Http\Request;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksi = Transaksi::all();
        return view('transaksi.index', compact('transaksi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kontrakans = Kontrakan::all();
        $penyewas = Penyewa::all();
        return view('transaksi.create', compact('kontrakans', 'penyewas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tgl_sewa' => 'required',
            'harga' => 'required',
            'jenis_sewa' => 'required',
            'penyewa_id' => 'required',
            'kontrakan_id' => 'required'
        ]);

        $transaksi = Transaksi::create([
            "tgl_sewa" => $request["tgl_sewa"],
            "harga" => $request["harga"],
            "jenis_sewa" => $request["jenis_sewa"],
            "penyewa_id" => $request["penyewa_id"],
            "kontrakan_id" => $request["kontrakan_id"],
        ]);
        return redirect('/transaksi')->with('success', 'Berhasil Menambahkan Tranksaksi Baru!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaksi = Transaksi::find($id);
        $date = date_create($transaksi->tgl_sewa);
        $transaksi->tgl_sewa = date_format($date, "d/m/Y");
        return view('transaksi.show', compact('transaksi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $transaksi = Transaksi::find($id);
        $kontrakans = Kontrakan::all();
        $penyewas = Penyewa::all();
        return view('transaksi.edit', compact('transaksi', 'kontrakans', 'penyewas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'tgl_sewa' => 'required',
            'harga' => 'required',
            'jenis_sewa' => 'required',
            'penyewa_id' => 'required',
            'kontrakan_id' => 'required'
        ]);

        $update = Transaksi::where('id', $id)->update([
            "tgl_sewa" => $request["tgl_sewa"],
            "harga" => $request["harga"],
            "jenis_sewa" => $request["jenis_sewa"],
            "penyewa_id" => $request["penyewa_id"],
            "kontrakan_id" => $request["kontrakan_id"],
        ]);
        return redirect('/transaksi')->with('success', 'Berhasil Merubah Data Transaksi!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Transaksi::destroy($id);
        return redirect('/transaksi')->with('success', 'Data Transaksi Berhasil Dihapus');
    }
}

resources/views/transaksi/create.blade.php
@extends('layouts.master')
@section('content')

<div class="ml-3 mt-3">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Membuat Transaksi Baru</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/transaksi" method="POST">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="tgl_sewa">Tanggal Sewa</label>
                        <input type="date" class="form-control" id="tgl_sewa" name="tgl_sewa" value="{{ old('tgl_sewa', '') }}>
                        @error('tgl_sewa')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="harga">Harga</label>
                        <input type="number" class="form-control" id="harga" name="harga" value="{{ old('harga', '') }}">
                        @error('harga')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="jenis_sewa">Jenis Sewa</label>
                        <select class="form-control" name="jenis_sewa" id="jk">
                            <option value="">-- Pilih Jenis Sewa Kontrakan Anda --</option>
                            <option value="1_bulan">1 Bulan</option>
                        </select>
                        @error('jk')
                            <span class="invalid-feedback" jk="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="penyewa_id">Penyewa</label>
                        <select class="form-control" id="platform" name="penyewa_id">
                            @foreach ($penyewas as $penyewa)
                                <option value="{{ $penyewa->id }}">{{ $penyewa->name }}</option>
                            @endforeach
                        </select>
                        @error('penyewa_id')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="kontrakan_id">Kontrakan</label>
                        <select class="form-control" id="platform" name="kontrakan_id">
                            @foreach ($kontrakans as $kontrakan)
                                <option value="{{ $kontrakan->id }}">{{ $kontrakan->name }}</option>
                            @endforeach
                        </select>
                        @error('kontrakan')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
     </div>
</div>

@endsection

resources/views/transaksi/edit.blade.php
@extends('layouts.master')
@section('content')

    <div class="ml-3 mt-3">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Data Transaksi {{ $transaksi->id }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form action="/transaksi/{{ $transaksi->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="tgl_sewa">Tanggal Sewa</label>
                        <input type="date" class="form-control" id="tgl_sewa" name="tgl_sewa"
                            value="{{ old('tgl_sewa', $transaksi->tgl_sewa) }}"
                            placeholder="Masukkan Nama Kontrakan Anda">
                        @error('tgl_sewa')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="harga">Harga</label>
                        <input type="number" class="form-control" id="harga" name="harga"
                            value="{{ old('harga', $transaksi->harga) }}">
                        @error('harga')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="jenis_sewa">Jenis Sewa</label>
                        <input type="text" class="form-control" id="jenis_sewa" name="jenis_sewa"
                            value="{{ old('jenis_sewa', $transaksi->jenis_sewa) }}"
                            placeholder="Masukkan Jenis Sewa Kontrakan Anda">
                        @error('jenis_sewa')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="penyewa">Penyewa</label>
                        <select class="form-control" id="penyewa" name="penyewa_id">
                            @foreach ($penyewas as $penyewa)
                                <option value="{{ $penyewa->id }}"
                                    {{ $transaksi->penyewa_id == $penyewa->id ? 'selected' : '' }}>{{ $penyewa->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('penyewa')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="kontrakan">Kontrakan</label>
                        <select class="form-control" id="kontrakan" name="kontrakan_id">
                            @foreach ($kontrakans as $kontrakan)
                                <option value="{{ $kontrakan->id }}"
                                    {{ $transaksi->kontrakan_id == $kontrakan->id ? 'selected' : '' }}>
                                    {{ $kontrakan->name }}
                                </option>
                            @endforeach
                        </select>
                        @error('kontrakan')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/transaksi/index.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Daftar Transaksi</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      @if (session('success'))
          <div class="alert alert-success">
            {{( session ('success'))}}
          </div>
      @endif
      <a class="btn btn-info mb-4" href="{{ route('transaksi.create') }}">
        Sewa Kontrakan Baru
      </a>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th>Tanggal Sewa</th>
            <th>Harga</th>
            <th>Jenis Sewa</th>
            <th>Penyewa</th>
            <th>Kontrakan</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($transaksi as $key => $transaksi)
            <tr>
              <td> {{ $key + 1 }} </td>
              <td> {{ $transaksi->tgl_sewa }} </td>
              <td> {{ $transaksi->harga }} </td>
              <td> {{ $transaksi->jenis_sewa }} </td>
              <td> {{ $transaksi->penyewa->name }} </td>
              <td> {{ $transaksi->kontrakan->name }} </td>
              @auth
              <td style="display : flex;"> 
                <a href="{{route('transaksi.show', ['transaksi' => $transaksi->id])}}" class="btn btn-info btn-sm"> Lihat </a>
                <a href="{{route('transaksi.edit', ['transaksi' => $transaksi->id])}}" class="btn btn-default btn-sm"> Edit </a>
                <form action="{{route('transaksi.destroy', ['transaksi' => $transaksi->id ])}}" method="post">
                  @csrf
                  @method('DELETE')
                  <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
              </td>
            </tr>
              @endauth
            @empty
              <tr>
                <td colspan="7" align="center"> Tidak Ada Daftar Transaksi </td>
              </tr>
          @endforelse
        </tbody>
      </table>
      
    </div>
    <!-- /.card-body -->
  </div>
</div>
@endsection

resources/views/transaksi/show.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
    <h2> Details Transaksi </h2>
    <p> {{ $transaksi->tgl_sewa }} </p>
    <p> Rp.{{ $transaksi->harga }} </p>
    <p> {{ $transaksi->jenis_sewa }} </p>
    <p> {{ $transaksi->penyewa->name }} </p>
    <p> {{ $transaksi->kontrakan->name }} </p>
</div>
@endsection