routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('kontrakan', 'KontrakanController');
Route::resource('pemilik', 'PemilikController')->middleware('checkRole:pemilik');;
Route::resource('transaksi', 'TransaksiController');
Route::resource('penyewa', 'PenyewaController');

app/Penyewa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Penyewa extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    
    protected $table = "penyewa";
    protected $fillable = ["name", "jk", "alamat", "email", "no_hp", "no_ktp", "pekerjaan", "foto", "user_id"];

}

app/Http/Controllers/PenyewaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Kontrakan;
use App\Penyewa;
use Auth;
use File;

class PenyewaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index','show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $penyewas = Penyewa::all();
        return view('penyewa.index', compact('penyewas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('penyewa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'jk'=>'required',
            'alamat'=>'required',
            'email'=>'required',
            'no_hp'=>'required',
            'no_ktp'=>'required',
            'pekerjaan'=>'required',
            'foto'=>'required|mimes:jpeg,jpg,png|max:2200'
        ]);

        $gambar = $request->foto;
        $new_gambar = time() . ' - ' . $gambar->getClientOriginalName();

        $penyewa = Penyewa::create([
            "name"=>$request->name,
            "jk"=>$request["jk"],
            "alamat"=>$request["alamat"],
            "email"=>$request["email"],
            'no_hp'=>$request->no_hp,
            'no_ktp'=>$request->no_ktp,
            "pekerjaan"=>$request["pekerjaan"],
            "foto"=>$new_gambar
        ]);
        $gambar -> move('img/penyewa/', $new_gambar);
        return redirect('/penyewa')->with('success', 'Berhasil Menambahkan Penyewa Baru!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $penyewa = Penyewa::find($id);
        return view('penyewa.show', compact('penyewa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $penyewa = Penyewa::find($id);
        return view('penyewa.edit', compact('penyewa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'jk'=>'required',
            'alamat'=>'required',
            'email'=>'required',
            'no_hp'=>'required',
            'no_ktp'=>'required',
            'pekerjaan'=>'required',
            'foto'=>'mimes:jpeg,jpg,png|max:2200'
        ]);

        $penyewa = Penyewa::findorfail($id);
        
        if($request->has('foto')){
            $path = 'img/penyewa/';
            File::delete($path . $penyewa->foto);
            $gambar = $request->foto;
            $new_gambar = time() . ' - ' . $gambar->getClientOriginalName();
            $gambar->move($path, $new_gambar);
            $penyewa_data = [
                'name'=>$request->name,
                'jk'=>$request->jk,
                'alamat'=>$request->alamat,
                'no_hp'=>$request->no_hp,
                'no_ktp'=>$request->no_ktp,
                'pekerjaan'=>$request->pekerjaan,
                'foto'=>$new_gambar
            ];
        } else{
            $penyewa_data = [
                'name'=>$request->name,
                'jk'=>$request->jk,
                'alamat'=>$request->alamat,
                'no_hp'=>$request->no_hp,
                'no_ktp'=>$request->no_ktp,
                'pekerjaan'=>$request->pekerjaan
            ];
        }
        $penyewa->update($penyewa_data);
        return redirect('/penyewa')->with('success', 'Berhasil Merubah Data penyewa!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $penyewa = Penyewa::findorfail($id);
        $penyewa -> delete();

        $path = "img/penyewa/";
        File::delete($path . $penyewa->foto);
        return redirect('/penyewa')->with('success', 'Data penyewa  Berhasil Dihapus');
    }
}

resources/views/penyewa/create.blade.php
@extends('layouts.master')
@section('content')

<div class="ml-3 mt-3">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Daftar Sebagai Penyewa Baru</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/penyewa" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Nama penyewa</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ Auth::user()->name }}" placeholder="Masukkan Nama Anda">
                        @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="jk">Jenis Kelamin</label>
                        <select class="form-control" name="jk" id="jk">
                            <option value="">-- Pilih Jenis Kelamin Anda --</option>
                            <option value="pria">Pria</option>
                            <option value="wanita">Wanita</option>
                        </select>
                        @error('jk')
                            <span class="invalid-feedback" jk="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" value="{{ old('alamat', '') }}" placeholder="Masukkan Alamat Anda">
                        @error('alamat')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="{{ old('email', '') }}" placeholder="Masukkan Alamat Email Anda">
                        @error('email')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="no_hp">No HP</label>
                        <input type="text" class="form-control" id="no_hp" name="no_hp" value="{{ old('no_hp', '') }}" placeholder="Masukkan No HP Anda">
                        @error('no_hp')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">No KTP</label>
                        <input type="text" class="form-control" id="no_ktp" name="no_ktp" value="{{ old('no_ktp', '') }}" placeholder="Masukkan No KTP Anda">
                        @error('no_ktp')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="pekerjaan">Pekerjaan</label>
                        <input type="text" class="form-control" id="pekerjaan" name="pekerjaan" value="{{ old('pekerjaan', '') }}" placeholder="Masukkan Pekerjaan Anda">
                        @error('pekerjaan')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="foto">Foto</label>
                        <input type="file" class="form-control" id="foto" name="foto">
                        @error('foto')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
     </div>
</div>

@endsection

resources/views/penyewa/edit.blade.php
@extends('layouts.master')
@section('content')

<div class="ml-3 mt-3">
    <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Data Penyewa {{ $penyewa->name }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/penyewa/{{ $penyewa->id }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Nama penyewa</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $penyewa->name }}" placeholder="Masukkan Nama Anda">
                        @error('name')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="jk">Jenis Kelamin</label>
                        <select class="form-control" name="jk" id="jk">
                            <option value="">-- Pilih Jenis Kelamin Anda --</option>
                            <option value="pria">Pria</option>
                            <option value="wanita">Wanita</option>
                        </select>
                        @error('jk')
                            <span class="invalid-feedback" jk="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" class="form-control" id="alamat" name="alamat" value="{{ $penyewa->alamat }}" placeholder="Masukkan Alamat Anda">
                        @error('alamat')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="{{ $penyewa->email }}" placeholder="Masukkan Alamat Email Anda">
                        @error('email')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="no_hp">No HP</label>
                        <input type="text" class="form-control" id="no_hp" name="no_hp" value="{{ $penyewa->no_hp }}" placeholder="Masukkan No HP Anda">
                        @error('no_hp')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">No KTP</label>
                        <input type="text" class="form-control" id="no_ktp" name="no_ktp" value="{{ $penyewa->no_ktp }}" placeholder="Masukkan No KTP Anda">
                        @error('no_ktp')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="pekerjaan">Pekerjaan</label>
                        <input type="text" class="form-control" id="pekerjaan" name="pekerjaan" value="{{ $penyewa->pekerjaan }}" placeholder="Masukkan Pekerjaan Anda">
                        @error('pekerjaan')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="foto">Foto</label>
                        <input type="file" class="form-control" id="foto" name="foto">
                        @error('foto')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
     </div>
</div>

@endsection

resources/views/penyewa/index.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Daftar Penyewa Kontrakan</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      @if (session('success'))
          <div class="alert alert-success">
            {{( session ('success'))}}
          </div>
      @endif
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th style="width: 200px">Nama Penyewa</th>
            <th>Jenis Kelamin</th>
            <th>Alamat</th>
            <th>Email</th>
            <th>No HP</th>
            <th>No KTP</th>
            <th>Pekerjaan</th>
            <th>Foto</th>
            <th style="width: 120px">Actions</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($penyewas as $key => $penyewa)
            <tr>
              <td> {{ $key + 1 }} </td>
              <td> {{ $penyewa->name }} </td>
              <td> {{ $penyewa->jk }} </td>
              <td> {{ $penyewa->alamat }} </td>
              <td> {{ $penyewa->email }} </td>
              <td> {{ $penyewa->no_hp }} </td>
              <td> {{ $penyewa->no_ktp }} </td>
              <td> {{ $penyewa->pekerjaan }} </td>
              <td> <img src="{{ asset('img/penyewa/'. $penyewa->foto) }}" width="100px" alt="..."> </td>
              @auth
              <td style="display : flex;"> 
                <a href="{{route('penyewa.show', ['penyewa' => $penyewa->id])}}" class="btn btn-info btn-sm"> Lihat </a>
                <a href="{{route('penyewa.edit', ['penyewa' => $penyewa->id])}}" class="btn btn-default btn-sm"> Edit </a>
                <form action="{{route('penyewa.destroy', ['penyewa' => $penyewa->id ])}}" method="post">
                  @csrf
                  @method('DELETE')
                  <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
              </td>
            </tr>
              @endauth
              @guest
              <td style="display : flex;"> 
              <a href="{{route('penyewa.show', ['penyewa' => $penyewa->id])}}" class="btn btn-info btn-sm"> Lihat </a>
              </td>
              @endguest
            @empty
              <tr>
                <td colspan="6" align="center"> Tidak Ada Daftar Penyewa </td>
              </tr>
          @endforelse
        </tbody>
      </table>
      <a class="btn btn-info mt-4" href="{{ route('penyewa.create') }}">
        Daftar Sebagai Penyewa Kontrakan Baru
      </a>
    </div>
    <!-- /.card-body -->
  </div>
</div>


@endsection

resources/views/penyewa/show.blade.php
@extends('layouts.master')
@section('content')
<div class="ml-3 mt-3">
    <h2> Details Penyewa </h2>
    <p> {{ $penyewa->name }} </p>
    <p> {{ $penyewa->alamat }} </p>
    <p> {{ $penyewa->email }} </p>
</div>
@endsection